name: Deploy to VPS

on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'prod' || github.ref == 'refs/heads/staging' && 'staging' || 'dev' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Set Environment Variables
        run: |
          echo "VPS_SSH_USER=ec2-user" >> $GITHUB_ENV
          echo "VPS_IP=54.179.53.222" >> $GITHUB_ENV
          echo "DEPLOY_DIR=/var/www/nexus" >> $GITHUB_ENV

      - name: Deploy Code & Setup Nginx
        run: ssh $VPS_SSH_USER@$VPS_IP 'bash -s' < .github/scripts/deploy.sh
