name: Deploy to VPS

on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/master' && 'prod' || github.ref == 'refs/heads/staging' && 'staging' || 'dev' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          if [[ -z "${{ env.VPS_IP }}" ]]; then
            echo "Error: VPS_IP is not set!" >&2
            exit 1
          fi
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts 2>/dev/null || echo "Warning: ssh-keyscan failed, proceeding anyway"
          chmod 644 ~/.ssh/known_hosts
      
      - name: Deploy Code
        run: ssh $VPS_SSH_USER@$VPS_IP 'bash -s' < .github/scripts/deploy.sh
